# Week 1 - Day 3
# NumPy & Pandas Deep Dive

## Objective
The objective of this notebook is to practice NumPy and Pandas operations including array creation, statistics, reshaping, slicing, broadcasting, data loading, data cleaning, and data merging.

In [1]:
import numpy as np
import pandas as pd

print("Libraries Imported Successfully")

Libraries Imported Successfully

# NumPy Practice
## Array Creation

In [2]:
numbers = np.random.randint(1, 101, 20)

print("Random Numbers:")
print(numbers)

Random Numbers:
[62 28 85 18 82 21  7 60 76 44 62 57 95 70 96 97 14 40  2 54]

## Statistics Calculation

In [3]:
print("Mean:", np.mean(numbers))
print("Median:", np.median(numbers))
print("Standard Deviation:", np.std(numbers))
print("Minimum:", np.min(numbers))
print("Maximum:", np.max(numbers))

Mean: 53.5
Median: 58.5
Standard Deviation: 29.84711041290262
Minimum: 2
Maximum: 97

## Reshaping Arrays

In [4]:
matrix = numbers.reshape(4, 5)

print(matrix)

[[62 28 85 18 82]
 [21  7 60 76 44]
 [62 57 95 70 96]
 [97 14 40  2 54]]

## Array Slicing

In [5]:
print(matrix[:2])

[[62 28 85 18 82]
 [21  7 60 76 44]]

## Broadcasting

In [6]:
broadcasted = matrix * 2

print(broadcasted)

[[124  56 170  36 164]
 [ 42  14 120 152  88]
 [124 114 190 140 192]
 [194  28  80   4 108]]

# Pandas Practice
## Data Loading

In [8]:
df = pd.read_csv("../data/titanic.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Dataset Inspection

In this section, we inspect the structure of the dataset including shape, columns, data types, and statistical information.

In [9]:
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

Dataset Shape:
(891, 12)

Column Names:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Data Types:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# Missing Values Analysis

Checking missing values present in the dataset.

In [11]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Data Cleaning

Handling missing values and removing duplicate records.

In [12]:
df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

df["Embarked"] = df["Embarked"].fillna(
    "Unknown"
)

df["Cabin"] = df["Cabin"].fillna(
    "Not Available"
)

df = df.drop_duplicates()

print(
    "Cleaning Completed Successfully"
)

Cleaning Completed Successfully

In [13]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# Data Type Verification

Verifying data types after cleaning.

In [14]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# Data Merging

Merging Titanic dataset with department information dataset.

In [15]:
department_df = pd.read_csv(
    "../data/department_info.csv"
)

department_df.head()

   Pclass      Department
0       1     First Class
1       2  Business Class
2       3   Economy Class

In [16]:
merged_df = pd.merge(
    df,
    department_df,
    on="Pclass",
    how="left"
)

merged_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Department
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Not Available,S,Economy Class
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,First Class
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Not Available,S,Economy Class
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,First Class
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Not Available,S,Economy Class

# Merged Dataset Information

Checking shape and columns after merging.

In [17]:
print("Merged Shape:")
print(merged_df.shape)

print("\nColumns:")
print(merged_df.columns)

Merged Shape:
(891, 13)

Columns:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Department'],
      dtype='object')

# Dataset Summary

Generating complete statistical summary of the dataset.

In [18]:
merged_df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Department
count,891.000000,891.000000,891.000000,891,891,891.000000,891.000000,891.000000,891,891.000000,891,891,891
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,148,4,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,Not Available,S,Economy Class
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,687,644,491
mean,446.000000,0.383838,2.308642,NaN,NaN,29.361582,0.523008,0.381594,NaN,32.204208,NaN,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,13.019697,1.102743,0.806057,NaN,49.693429,NaN,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,22.000000,0.000000,0.000000,NaN,7.910400,NaN,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,35.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN,NaN

# Conclusion

This notebook demonstrated:

- NumPy array operations
- Statistical calculations
- Array reshaping
- Array slicing
- Broadcasting
- Data loading using Pandas
- Data inspection
- Missing value handling
- Data cleaning
- Data merging
- Dataset summarization

These techniques are fundamental for Data Science and Machine Learning workflows.